version: "3.6"
services:
  influxdb:
    image: influxdb:2.1
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_storage:/var/lib/influxdb2
      - ./data:/data
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=telegraf
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
    #      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=
  telegraf:
    image: telegraf:1.21.4
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - "50002:50002/tcp"
      - "50001:50001/tcp"

  grafana:
    image: grafana/grafana:8.4.1
    restart: always
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - "80:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./dashboards:/etc/dashboards
      - ./grafana.ini:/etc/grafana/grafana.ini

volumes:
  grafana_storage: {}
  influxdb_storage: {}

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
