version: "3.9"
services:
  influxdb2:
    image: influxdb:2.1
    container_name: influxdb2
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_storage:/var/lib/influxdb2
      - ./data:/data
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=hfAiqJWyaWQnkWyZ01M8Sb4un2Lb3LA3kyyB0vOVOt8SqMt8MtCN2EObC5QzwOxgkiEgajRaz-Xy-_arMOYOFQ==
  telegraf:
    image: telegraf:1.21.1
    container_name: telegraf
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

    depends_on:
      - influxdb2
    links:
      - influxdb2

    restart: always

  grafana:
    image: grafana/grafana:8.4.1
    container_name: grafana
    restart: always
    depends_on:
      - influxdb2
    env_file: configuration.env
    links:
      - influxdb2
    ports:
      - "80:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./dashboards:/etc/dashboards
      - ./grafana.ini:/etc/grafana/grafana.ini

volumes:
  grafana_storage: {}
  influxdb_storage: {}

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
